config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :venues, except: [:create] do 
    resources :reviews
  end

  resources :venues, only: [:create] do
    resources :venue_parts, only: [:edit, :update]
  end

  root to: "venues#index"

end

app/models/factual_venues.rb
class FactualVenues
  require 'factual'
  require 'ostruct'

  @@client = Factual.new(Rails.application.secrets.factual_key, Rails.application.secrets.factual_secret)

  def self.client
    @@client
  end

  def self.search_for(query:, around: "St. Louis")
    results = @@client.table("places-us").search(query).filters("locality" => around).rows
    turn_into_ostruct(results)
  end

  def self.turn_into_ostruct(array)
    all_results = []
    array.each { |result| all_results << OpenStruct.new(result) }
    all_results
  end

  def self.find(factual_id)
    result = [ @@client.table("places-us").row(factual_id) ]
    turn_into_ostruct(result).first
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :venue

  validates :user_id, :venue_id, :wifi_quality, :coffee_quality, :coffee_price, :chair_drag_loudness, :outlets_available, :temperature, presence: true
  validates_inclusion_of :wifi_quality, :coffee_quality, :coffee_price, :chair_drag_loudness, :outlets_available, :temperature, :in => 1..3

  WIFI_QUALITY_SCALE = [ "reference docs only", "spotify works", "gifs galore"]
  COFFEE_QUALITY_SCALE = ["icky", "adequate", "amazing"]
  COFFEE_PRICE_SCALE = ["pricy", "affordable", "marvelous"]
  CHAIR_DRAG_LOUDNESS_SCALE = ["earbleed city", "typical cafe", "symphonic silence"]
  OUTLETS_AVAILABLE_SCALE = ["no outlets", "some outlets", "bountiful outlets"]
  TEMPERATURE_SCALE = ["bring your wardrobe", "50/50", "always on point"]


  def generate_options(scale)
    result = {}
    scale.each_with_index do |k, i|
      result[k] = i+1
    end
    result
  end

end

app/models/search.rb
class Search
  def self.execute(params)
    query = params[:query]
    facet = params[:facet] || "overall_rating"

    unless query
      facet_search(facet)
    else
      query_search(query)
    end
  end

  def self.facet_search(facet)
    Venue.search do
      order_by(facet.to_sym, :desc)
    end.results
  end

  def self.query_search(query)
    Venue.search do
      fulltext query
    end.results
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  has_many :reviews

  ATTRIBUTES = %w[wifi_quality coffee_quality coffee_price chair_drag_loudness outlets_available temperature]

  searchable do
    integer :wifi_quality
    integer :coffee_quality
    integer :coffee_price
    integer :chair_drag_loudness
    integer :outlets_available
    integer :temperature
    integer :overall_rating
    integer :review_count
    latlon(:location) { Sunspot::Util::Coordinates.new(lat, lng) }
    text :name
    text :awesome_people do
      reviews.pluck(:awesome_people)
    end
    text :comments do
      reviews.pluck(:comment)
    end
  end

  ATTRIBUTES.each do |attribute|
    define_method(attribute.to_sym) do
      aggregate_rating_for(attribute.to_s)
    end
  end

  def aggregate_rating_for(attribute)
    return 0 unless reviews.any?

    total = reviews.pluck(attribute.to_sym).compact.sum
    average = total.to_f / reviews.count
    average.round(0)
  end

  def overall_rating
    return 0 unless reviews.any?

    ratings = ATTRIBUTES.map {|attr| aggregate_rating_for(attr) }
    ratings.sum.to_f / ATTRIBUTES.length
  end

  def review_count
    reviews.count
  end

  def populate_from_factual
    result = FactualVenues.find(factual_id)
    update(
      name: result.name,
      address: result.address,
      city: result.locality,
      lat: result.latitude,
      lng: result.longitude,
      country: result.country,
      website: result.website,
      phone: result.phone,
      zip: result.postcode,
      hours: result.hours,
      hours_display: result.hours_display,
      state: result.region,
      neighborhood: result.neighborhood
    )

    Venue.where(factual_id: factual_id).where.not(id: id).destroy_all
  end

  def display_address
    [address, city, state, zip].join(", ")
  end

end

app/models/venue/selection.rb
class Venue::Selection < Venue

  def results
    FactualVenues.search_for(query: name)
  end
end

app/models/wifi_rating.rb
class WifiRating < ActiveRecord::Base
  enum quality: { text: 1, pics: 2, gifs: 3, streaming: 4 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_venue
  before_action :set_review, except: [:new, :create]

  def new
    if current_user.reviews.where(venue_id: @venue.id).any?
      redirect_to edit_venue_review_path(@venue, current_user.reviews.where(venue_id: @venue.id).first)
    end
    @review = current_user.reviews.new
  end

  def edit
  end

  def create
    @review = current_user.reviews.new review_params
    if @review.save
      redirect_to venue_path(@venue)
    else
      render "new"
    end
  end

  def update
    @review.update review_params
    if @review.save
      redirect_to venue_path(@venue)
    else
      render "edit"
    end
  end

  def destroy
  end

  private
    def set_venue
      @venue = Venue.find(params[:venue_id])
    end

    def set_review
      @review = Review.find(params[:id])
      unless current_user.reviews.include?(@review)
        redirect_to :back, "You can only edit your own views"
      end
    end

    def review_params
      params.require(:review).permit(:user_id, :venue_id, :wifi_quality, :coffee_quality, :coffee_price, :chair_drag_loudness, :outlets_available, :temperature, :awesome_people, :comment)
    end
end

app/controllers/venue_parts_controller.rb
class VenuePartsController < ApplicationController
  before_action :authenticate_user!, :set_venue

  STEPS = ['name', 'selection']

  def edit
    if step.present?
      render step
    else
      render nothing: true, status: 404
    end
  end

  def update
    if @venue.update venue_params
      if next_step
        redirect_to edit_venue_venue_part_path(@venue, next_step)
      else
        @venue.populate_from_factual
        redirect_to venue_path(@venue)
      end
    end
  end

  private

  def set_venue
    @venue = wizard_step_partner
  end

  def wizard_step_partner
    venue_class = "Venue::#{step.camelcase}".constantize rescue Venue
    venue_class.find(params[:venue_id])
  end

  def step
    STEPS.find { |a_step| a_step == params[:id].to_s.downcase }
  end

  def next_step
    current_step_index = STEPS.index(step)
    next_step = STEPS[current_step_index +1]
  end

  def venue_params
    params.require(:venue).permit(:name, :factual_id )
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @venues = Search.execute(params)

    @emphasis = params[:facet] || :overall_rating

    @hash = Gmaps4rails.build_markers(@venues) do |venue, marker|
      marker.lat venue.lat
      marker.lng venue.lng
      marker.infowindow venue.name
    end
  end

  def show
    @venue = Venue.find(params[:id])
  end

  def create
    @venue = Venue.create
    redirect_to edit_venue_venue_part_path(@venue, VenuePartsController::STEPS.first )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/venue_parts_helper.rb
module VenuePartsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>CodingCoffee</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
</head>
<body>
<%= render "shared/navbar" %>
<% if notice %>
  <div class="temp alert alert-info alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= notice %>
</div>
    <% end %>

<% if alert %>
  <div class="temp alert alert-warning alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= alert %>
</div>
    <% end %>  <%= evil_icons_sprite %>
<body class="<%= yield :body_class %>">
<%= yield %>
</body>
</html>

app/views/reviews/_form.html.erb
<%= form_for [@venue, @review] do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited your wisdom from the tubes:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :venue_id, value: @venue.id %>
  <div>
    <%= f.label :wifi_quality, "Wifi Quality:" %>
    <%= f.select :wifi_quality, options_for_select(@review.generate_options(Review::WIFI_QUALITY_SCALE), @review.wifi_quality), include_blank: true %>
  </div>
  <div>
    <%= f.label :coffee_quality, "Coffee Quality:" %>
    <%= f.select :coffee_quality, options_for_select(@review.generate_options(Review::COFFEE_QUALITY_SCALE), @review.coffee_quality), include_blank: true %>
  </div>
  <div>
    <%= f.label :coffee_price, "Coffee Price:" %>
    <%= f.select :coffee_price, options_for_select(@review.generate_options(Review::COFFEE_PRICE_SCALE), @review.coffee_price), include_blank: true %>
  </div>
  <div>
    <%= f.label :chair_drag_loudness, "Chair Drag Loudness:" %>
    <%= f.select :chair_drag_loudness, options_for_select(@review.generate_options(Review::CHAIR_DRAG_LOUDNESS_SCALE), @review.chair_drag_loudness), include_blank: true %>
  </div>
  <div>
    <%= f.label :outlets_available, "Outlest Available:" %>
    <%= f.select :outlets_available, options_for_select(@review.generate_options(Review::OUTLETS_AVAILABLE_SCALE), @review.outlets_available), include_blank: true %>
  </div>
  <div>
    <%= f.label :temperature, "Temperature:" %>
    <%= f.select :temperature, options_for_select(@review.generate_options(Review::TEMPERATURE_SCALE), @review.temperature), include_blank: true %>
  </div>
  <div>
    <%= f.label :awesome_people, "Any awesome people there?" %><br />
    <%= f.text_area :awesome_people %>
  </div>
  <div>
    <%= f.label :comment, "Anything else you'd like to add?" %><br />
    <%= f.text_area :comment%>
  </div>

  <%= f.submit "Bequeath Judgement" %>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Appraising: <%= @venue.name %></h1>

<%= render partial: "form" %>

app/views/reviews/new.html.erb
<h1>Appraising: <%= @venue.name %></h1>

<%= render partial: "form" %>

app/views/reviews/update.html.erb
<h1>Reviews#update</h1>
<p>Find me in app/views/reviews/update.html.erb</p>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <div class="row">
        <div class="col-xs-6">
          <form action="/" method="get" class="navbar-form navbar-left">
            <div class="input-group">
              <input type="text" name="query" class="form-control input-xLarge" id="navbar-search-input" value=<%= params[:query] %>> 
              <div class="input-group-btn">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false" id="navbar-search-button">
                  <div id="navbar-search-options">
                    <%= evil_icon 'ei-chevron-down', size: :s %>
                  </div>
                  <div id="navbar-search-cancel">
                    <%= evil_icon 'ei-close-o', size: :s %>
                  </div>
                </button>
                <!-- I use id's instead of classes for most of my css because I have no idea what I'm doing. forgive me D: -->
                <ul class="dropdown-menu dropdown-menu-right" id="navbar-search-dropdown" role="menu">
                  <li><%= link_to "highest rated", venues_path(facet: "overall_rating") %></li>
                  <li><%= link_to "best coffee", venues_path(facet: "coffee_quality") %></li>
                  <li><%= link_to "best wifi", venues_path(facet: "wifi_quality") %></li>
                  <li><%= link_to "outlet coverage", venues_path(facet: "outlets_available") %></li>
                  <li><%= link_to "most reviewed", venues_path(facet: "review_count") %></li>
                  <li class="divider"></li>
                  <li><a href="#">closest to me</a></li>
                  <li><a href="#">open latest</a></li>
                  <li><a href="#">open earliest</a></li>
                </ul>
              </div><!-- /btn-group -->
            </div><!-- /input-group -->
          </form>
        </div><!-- /.col-lg-6 -->
      </div><!-- /.row -->
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#about">About</a></li>
        <li><%= link_to "Account", edit_user_registration_path(current_user) if user_signed_in? %></li>
        <li><%= link_to "Logout", destroy_user_session_path(current_user) if user_signed_in? %></li>
        <li><%= link_to "Sign Up", new_user_registration_path unless user_signed_in? %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/venue_parts/edit.html.erb
<h1>VenueParts#edit</h1>
<p>Find me in app/views/venue_parts/edit.html.erb</p>

app/views/venue_parts/name.html.erb
<div class="content">
  <header class="top container-fluid">
    <div class="container">
      <div class="col-sm-6 col-sm-offset-2">
        <%= form_for @venue, url: venue_venue_part_path(@venue.id, params[:id]), as: :venue do |f|%>
          <div>
            <%= f.label :name, "Name of Venue:" %>
            <%= f.text_field :name %>
          </div>
          <p>Currently for St. Louis Only</p>
          <%= f.submit "Next" %>
        <% end %>
      </div>
    </div><!-- end .container -->
  </section>
</div><!-- end #content -->

app/views/venue_parts/selection.html.erb
<div class="content">
  <header class="top container-fluid">
    <div class="container">
      <div class="col-sm-6 col-sm-offset-2">
        <%= form_for @venue, url: venue_venue_part_path(@venue.id, params[:id]), as: :venue do |f|%>
          <p> Confirm Results for <%= @venue.name %></p>

          <% @venue.results.each do |possible_venue| %>
            <div>
              <%= f.radio_button :factual_id, possible_venue.factual_id  %>
              <p><%= possible_venue.name %></p>
              <p><%= possible_venue.address %></p>
              <p><%= possible_venue.locality %></p>
              <p><%= link_to possible_venue.website, possible_venue.website %></p>
            </div>
          <% end %>
          <%= f.submit "Complete" %>
        <% end %>
      </div>
    </div><!-- end .container -->
  </section>
</div><!-- end #content -->

app/views/venue_parts/update.html.erb
<h1>VenueParts#update</h1>
<p>Find me in app/views/venue_parts/update.html.erb</p>

app/views/venues/_venue.html.erb
<div class="row venue-partial border">
  <div class="col-xs-9">
    <div class="row">
      <%= venue.send(locals[:emphasis]) %>
    </div>
    <div class="row">
      <%= venue.name %>
      <%= venue.display_address %>
    </div>
  </div>
  <div class="col-xs-3">
    <%= link_to venue_path(venue) do %>
      <%= evil_icon 'ei-chevron-right' %>
    <% end %>
  </div>
</div>

app/views/venues/index.html.erb
<div class="content">
  <header class="top container-fluid">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <%= render @venues, locals: {emphasis: @emphasis} %>
          <ul>
            <li><%= link_to "add a place", venues_path, method: :post %></li>  
          </ul>
        </div>

        <div class="col-md-9">
          <div style='width: 800px;'>
            <div id="map" style='width: 800px; height: 400px;'></div>
          </div>
        </div>
      </div>
    </div><!-- end .container -->
  </section>
</div><!-- end #content -->


<script type="text/javascript" charset="utf-8">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    });
</script>

app/views/venues/main.html.erb
<div class="content">
  <header class="top container-fluid">
    <div class="container">
      <div class="col-sm-6 col-sm-offset-2">
        <div class="form-group row">
          <%= form_tag results_venues_path, method: :get do %>
            <%= text_field_tag "search[query]" %>
            <%= submit_tag "Go", class: "btn btn-success" %>
          <% end %>

          <%= link_to "Add Restaurant", venues_path, method: :post %>
        </div>
      </div>
    </div><!-- end .container -->
  </section>
</div><!-- end #content -->

app/views/venues/show.html.erb
<div class="content">
  <header class="top container-fluid">
    <div class="container">
      <div class="col-sm-6 col-sm-offset-2">
        <h1><%= @venue.name %></h1>
        <%= link_to "What's it like to code here?", new_venue_review_path(@venue)  %>
      </div>
    </div><!-- end .container -->
  </section>
</div><!-- end #content -->